on:
  push:
    branches:
        - main
jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:

            - name: Setup Go
              id: install_go
              uses: actions/setup-go@v2
              with:
                go-version: '1.21'
            - name: Checkout Repo
              id: checkout_repo
              uses: actions/checkout@v3
            - name: Download Go Dependencies
              id: do_go_mod_tidy
              run: |
                go mod tidy
            - name: Install Fyne
              id: install_fyne
              run: |
                go get fyne.io/fyne/v2@latest
                go install fyne.io/fyne/v2/cmd/fyne@latest
            - name: Build WASM
              id: build_wasm
              env:
                JWT_SECRET: ${{secrets.JWT_SECRET}}
              run: |
                fyne package -os wasm -icon appIcon.png
            - name: Upload to S3
              uses: shallwefootball/s3-upload-action@master
              id: S3
              with:
                aws_key_id: ${{secrets.AWS_KEY_ID}}
                aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
                aws_bucket: yt-dl.gagecottom.com
                source_dir: wasm